packages:
  - "."

overrides:
  '@mikro-orm/core': 6.4.16
  '@mikro-orm/knex': 6.4.16
  '@mikro-orm/migrations': 6.4.16
  '@mikro-orm/postgresql': 6.4.16

allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
